#ifndef _JCERROR_H_
#define _JCERROR_H_

#define ERROR_ODD_COLUMNS_NOT_SUPPORTED									1
#define ERROR_ODD_ROWS_NOT_SUPPORTED									2
#define ERROR_INVALID_NUMBER_OF_LINES									3
#define ERROR_INVALID_SAMPLES_PER_LINE									4
#define ERROR_SOI_ALREADY_DETECTED										5
#define ERROR_INVALID_QUANTIZATION_TABLE_DESTINATION_SELECTOR			6
#define ERROR_UNSUPPORTED_IMAGE_FORMAT									7
#define ERROR_INVALID_QUANTIZATION_TABLE_DESTINATION_IDENTIFIER			8
#define ERROR_QUANTIZATION_TABLE_ELEMENT_ZERO							9
#define ERROR_INVALID_QUANTIZATION_TABLE_DEFINITION_LENGTH				10
#define ERROR_INVALID_TABLE_CLASS										11
#define ERROR_INVALID_NUMBER_OF_HUFFMAN_CODES							12
#define ERROR_BAD_HUFFMAN_TABLE											13
#define ERROR_INVALID_HUFFMAN_TABLE_DESTINATION_IDENTIFIER				14
#define ERROR_INVALID_HUFFMAN_CODE										15
#define ERROR_INVALID_DCT_COEFF											16
#define ERROR_HUFFCODE_OVERFLOW											17


#define JC_TERMINATED													105

#endif

